sudo: required
services:
  - docker

before_install:
  - docker build -t jibolaolu/docker-react -f Dockerfile.dev .
language: generic
script:
  - docker run  jibolaolu/docker-react npm run ci_test -- --coverageI
